#+title: All In Mobile

* 尊重用户，保留用户对产品的控制
  
  虽然整合了求是潮的全线产品，
  但是依然应该要让用户对产品有足够的控制权。
  整个实现应该要插件化，
  松耦合化，
  让用户自己选择安装或者禁用哪些功能，
  允许用户控制每个应用的顺序。
  总的来说，就是要保持整个应用的轻巧与高度可定制化。
  
* 平台的优势
  
** 减少推广成本

   首先，借助主打功能的粘性（比如课表、考试、成绩等功能），
   顺势推广求是潮的其他产品，
   比如Notice、Share、Voice、水朝夕的电子杂志等等，使得我们的产品能直接推广到五千用户的手里。
   这样就直接缩小的推广的成本。

   此外，利用Mobile的推送功能，
   我们可以推送消息到用户终端来进行推广。

** 增加用户粘性

   只要用户依赖我们整个平台的一个功能，
   就能够对我们的平台产生粘性。
   就能让用户离不开我们的应用。

** 吸引额外的开发者

   我们的Mobile作为一个开放平台而存在，
   借助我们在用户推广方面的优势，（既有的五千用户）
   可以直接吸引一些开发者过来。
   同时，作为一个生态系统，
   这样也能够使我们的平台增加对用户的粘性。
   从而使整个系统良性发展。

* 混合应用

** 基础功能
   
   目前手机站最重要，且使用人数最多的功能就是教务功能了，
   因此我们（技术-手机站项目组）决定将手机站的基础功能原生化，
   原生化的意义在于，
   由于安卓平台的性能有限，使用网页集成的方式将可能导致严重的性能问题，
   这样就没法做动画等功能了，会导致用户的操作感降低的比较严重；
   但原生化就可以解决这个问题，
   实现的时候，我们可以进行大量的优化工作，
   而且安卓本身对于原生程序的性能就非常高，
   因此就可以制作动画、手势跟随等富有操作感的功能。
   
** 扩展功能

   对于非核心库的功能，
   我们主要借助HTML5+JS来实现。
   类Web的开发方式为我们提供了极高扩展能力和快速开发能力。
   混合应用为我们提供了高性能和快速开发的能力。

* mobile和各产品之间的数据交互

** mobile和现有产品之间的数据交互

*** mobile和share

    mobile提供给share：
    个人课表信息；教师信息

    share提供给mobile：
    课程相关资料：包括课程资料数量；课件试卷等资料的下载链接

*** mobile和notice

    mobile提供给notice：
    个人空余时间

    notice提供给mobile：
    近期活动；活动抢票链接

*** mobile和box

    mobile上的功能：
    手机快速上传的小文件；文件快速下载链接
    
    box上的功能：
    无

** mobile和未来可能出现的产品之间的数据交互

*** mobile和voice
    
    mobile上的功能：
    歌曲录制上传；收藏/取消收藏歌曲；热门歌曲和歌手列表；歌曲试听
    
    voice上的功能：
    无

*** mobile和问卷调查系统

    mobile上的功能：
    手机做问卷；查看问卷数据
    
    问卷调查系统上的功能：
    无

*** mobile和投票站

    mobile上的功能：
    手机投票；投票信息

    投票站上的功能：
    无

*** mobile和社团网上报名平台

    mobile上的功能：
    手机网上报名；浏览社团信息
    
    社团网上报名平台上的功能：
    无

*** mobile和搜索引擎

    mobile上的功能：
    手机搜索
    
    搜索引擎上的功能：
    无

*** mobile和用户反馈系统

    mobile上的功能：
    手机提交反馈

    用户反馈系统上的功能：
    无

* 执行方案
  
** Step 1

*** 原生开发
    由 Mobile 项目组实现基本的底层框架以及核心功能。
    开发的同时，测试功能可用性及稳定性。

*** 确定API
    基于已有的Mobile的HTML5的代码以及对需求的分析来基本确定下一步插件机制所需要的API。
    同时利用新原生开发中的反馈，新增和调整API。
    在Step 1结束的时候应该基本敲定API与权限控制，整理出一份开发文档出来。

** Step 2
   构建平台，引入插件机制。

   由Mobile项目组辅助各个项目组实现与Mobile之间的整合。
   同时利用实践开发调整API。
   整理出一份完整详细的API文档。
   给出至少一份插件开发样例代码。
   为下一步做准备。

** Step 3
   开放平台，引入第三方开发者。

   开放Step2整理的文档和样例，搭建求是潮Mobile开放平台。
   搭建线上开放平台，同时提供PDF文档，方便开发者开发。

   同时收集开发者的反馈，适当增加一些新的API。
   此时调整API应慎重，应尽量避免破坏性变更。
