#+title: All In Mobile

* 尊重用户，保留用户对产品的控制

  虽然整合了求是潮的全线产品，
  但是依然应该要让用户对产品有足够的控制权。
  整个实现应该要插件化，
  松耦合化，
  让用户自己选择安装或者禁用哪些功能，
  允许用户控制每个应用的顺序。
  总的来说，就是要保持整个应用的轻巧与高度可定制化。

* 平台的优势

** 减少推广成本

   首先，借助主打功能的粘性（比如课表、考试、成绩等功能），
   顺势推广求是潮的其他产品，
   比如Notice、Share、Voice、水朝夕的电子杂志等等，使得我们的产品能直接推广到五千用户的手里。
   这样就直接缩小的推广的成本。

   此外，利用Mobile的推送功能，
   我们可以推送消息到用户终端来进行推广。

** 增加用户粘性

   只要用户依赖我们整个平台的一个功能，
   就能够对我们的平台产生粘性。
   就能让用户离不开我们的应用。

** 吸引额外的开发者

   我们的Mobile作为一个开放平台而存在，
   借助我们在用户推广方面的优势，（既有的五千用户）
   可以直接吸引一些开发者过来。
   同时，作为一个生态系统，
   这样也能够使我们的平台增加对用户的粘性。
   从而使整个系统良性发展。

* 执行方案
  
  由Mobile项目组实现一个基本框架，
  先实现核心功能，
  下一步实现平台，
  由Mobile项目组辅助各个项目组实现与Mobile的整合。

** 基础功能
    
    目前手机站最重要，且使用人数最多的功能就是教务功能了，
    因此我们（技术-手机站项目组）决定将手机站的基础功能原生化，
    原生化的意义在于，
    由于安卓平台的性能有限，使用网页集成的方式将可能导致严重的性能问题，
    这样就没法做动画等功能了，会导致用户的操作感降低的比较严重；
    但原生化就可以大幅度的解决这个问题，
    实现的时候，我们可以进行大量的优化工作，
    而且安卓本身对于原生程序的性能就非常高，
    因此就可以制作动画、手势跟随等富有操作感的功能。

** 扩展功能
    
    像之前所说的，我们在手机站上面开发一个平台，
    用这个平台，虽然可能导致我们在两个平台上面的开发成本增加，
    但是一旦实现了这个平台，我们将可以快速的开发各种插件，
    在两个平台之间就可以直接开发了；

** 平台化的未来
    
    